export const USER_SIGN_IN = 'USER_SIGN_IN'
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE'
export const USER_SIGN_IN_PENDING = 'USER_SIGN_IN_PENDING'
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS'

export const USER_SIGN_OUT = 'USER_SIGN_OUT'
export const USER_SIGN_OUT_FAILURE = 'USER_SIGN_OUT_FAILURE'
export const USER_SIGN_OUT_PENDING = 'USER_SIGN_OUT_PENDING'
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS'
